// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9LLHaC9z4fK_pJlaCIiYlIEmEJtqZVK4',
    appId: '1:518253249676:web:71c71fd05a7a68e10a27a9',
    messagingSenderId: '518253249676',
    projectId: 'sankalpacademy-66de9',
    authDomain: 'sankalpacademy-66de9.firebaseapp.com',
    storageBucket: 'sankalpacademy-66de9.firebasestorage.app',
    measurementId: 'G-DBEYB4KLY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtAsUdptZUemLv5h3HD36Y4lmFIxovd-U',
    appId: '1:518253249676:android:ed88a7d9f6861a2e0a27a9',
    messagingSenderId: '518253249676',
    projectId: 'sankalpacademy-66de9',
    storageBucket: 'sankalpacademy-66de9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0e5e3Qaet4elRDSdjco3NGdyH-PVdUPs',
    appId: '1:518253249676:ios:8743510b90cc72580a27a9',
    messagingSenderId: '518253249676',
    projectId: 'sankalpacademy-66de9',
    storageBucket: 'sankalpacademy-66de9.firebasestorage.app',
    iosBundleId: 'com.example.tution',
  );
}
